name: "CI"
on:
  push:
  pull_request:
jobs:
  pkgs-linux:
    strategy:
      matrix:
        infra: [nixpkgs, haskell-nix, shajra]
        set: [build, prebuilt]
    name: "pkgs-linux: ${{ matrix.infra }}: ${{ matrix.set }}"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          substituters = https://cache.iog.io
          trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: cachix/cachix-action@v12
      with:
        name: shajra
        signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
    - run: cat ~/.config/nix/nix.conf
    - run: |
        nix build --print-build-logs --verbose \
            .#ci.${{ matrix.set }}.${{ matrix.infra }}
    - run: |
        nix --print-build-logs path-info \
            .#ci.${{ matrix.set }}.${{ matrix.infra }}
  pkgs-darwin:
    strategy:
      matrix:
        infra: [nixpkgs, haskell-nix, shajra]
        set: [build, prebuilt]
    name: "pkgs-darwin: ${{ matrix.infra }}: ${{ matrix.set }}"
    needs: [pkgs-linux]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        # DESIGN: cache.nixos.org explicit because Magix Nix Cache not appending it
        extra-conf: |
          substituters = https://cache.iog.io https://cache.nixos.org
          trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
    # DESIGN: no Magic Nix Cache because pkgs-linux gets too close to API limit
    - uses: cachix/cachix-action@v12
      with:
        name: shajra
        signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
    - run: cat ~/.config/nix/nix.conf
    - run: |
        nix build --print-build-logs --verbose \
            .#ci.${{ matrix.set }}.${{ matrix.infra }}
    - run: |
        nix --print-build-logs path-info \
            .#ci.${{ matrix.set }}.${{ matrix.infra }}
  installers-linux:
    needs: [pkgs-linux]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          substituters = https://cache.iog.io
          trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: cachix/cachix-action@v12
      with:
        name: shajra
        signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
    - run: cat ~/.config/nix/nix.conf
    - run: |
        nix run .#nixosConfigurations.cake.nixos-rebuild -- \
                           --flake .#cake        build
    - run: |
        nix run .#nixosConfigurations.hole.nixos-rebuild -- \
                           --flake .#hole        build
    - run: ./home-manager  --flake .#cake-slim   build
    - run: ./home-manager  --flake .#hole-slim   build
    - run: ./home-manager  --flake .#shajra-slim build
